defmodule GlobalbridgeBackendWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :globalbridge_backend

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_globalbridge_backend_key",
    signing_salt: "DQ/n9hwz",
    same_site: "Lax"
  ]

  # WebSocket endpoint for real-time messaging
  socket("/socket", GlobalbridgeBackendWeb.UserSocket,
    websocket: [
      connect_info: [:peer_data, :x_headers],
      timeout: 45_000,
      # Optimize for low latency
      compress: false
    ],
    longpoll: false
  )

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :globalbridge_backend,
    gzip: not code_reloading?,
    only: GlobalbridgeBackendWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug(Phoenix.CodeReloader)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  # Request logging for security monitoring
  plug(Plug.Logger,
    log: :info,
    formatter: {Plug.Logger, :format},
    include_headers: ["authorization", "x-forwarded-for", "user-agent"],
    exclude_paths: ["/favicon.ico", "/robots.txt"]
  )

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)

  # CORS configuration
  if Mix.env() == :dev do
    plug(CORSPlug,
      origin: ["http://localhost:3000"],
      credentials: true,
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
      headers: ["Authorization", "Content-Type", "Accept", "X-CSRF-Token", "X-Requested-With"],
      max_age: 86400
    )
  else
    plug(CORSPlug,
      origin:
        System.get_env("ALLOWED_ORIGINS", "")
        |> String.split(",")
        |> Enum.map(&String.trim/1)
        |> Enum.reject(&(&1 == "")),
      credentials: true,
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
      headers: ["Authorization", "Content-Type", "Accept", "X-CSRF-Token", "X-Requested-With"],
      max_age: 86400
    )
  end

  plug(GlobalbridgeBackendWeb.Router)
end
