//
//  SmartReplySuggestion.swift
//  GlobalBridge
//
//  Created on 2025-10-25.
//

import Foundation

/// Represents a smart reply suggestion generated by the AI system
struct SmartReplySuggestion: Codable, Identifiable, Equatable {
    let id: UUID
    let type: String // "quick-reply", "contextual", "proactive"
    let content: String
    let confidence: Double // 0.0-1.0
    let position: Int
    let context: String
    let timestamp: Date

    /// Indicates if this suggestion is proactive (unsolicited)
    var isProactive: Bool {
        type == "proactive"
    }
}
