// Sample generated by grok-code-fast-1: Image resizing service
// Handles JPEG/PNG resizing to max 1024x768, integrates with AWS S3 for storage.
// Run with: go run main.go

package main

import (
    "bytes"
    "fmt"
    "image"
    _ "image/jpeg"
    _ "image/png"
    "io"
    "log"
    "os"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/s3"
    "github.com/nfnt/resize"
)

type ImageResizer struct {
    S3Client *s3.S3
    Bucket   string
}

func NewImageResizer(bucket string) *ImageResizer {
    sess := session.Must(session.NewSession())
    return &ImageResizer{
        S3Client: s3.New(sess),
        Bucket:   bucket,
    }
}

func (r *ImageResizer) ResizeAndUpload(key string, width, height uint) error {
    // Download from S3
    input := &s3.GetObjectInput{
        Bucket: aws.String(r.Bucket),
        Key:    aws.String(key),
    }
    obj, err := r.S3Client.GetObject(input)
    if err != nil {
        return fmt.Errorf("download failed: %w", err)
    }
    defer obj.Body.Close()

    // Decode image
    img, _, err := image.Decode(obj.Body)
    if err != nil {
        return fmt.Errorf("decode failed: %w", err)
    }

    // Resize
    m := resize.Resize(width, height, img, resize.Lanczos3)

    // Encode to buffer
    buf := new(bytes.Buffer)
    err = jpeg.Encode(buf, m, nil) // Or PNG
    if err != nil {
        return fmt.Errorf("encode failed: %w", err)
    }

    // Upload resized
    resizedKey := key + "_resized.jpg"
    uploadInput := &s3.PutObjectInput{
        Bucket: aws.String(r.Bucket),
        Key:    aws.String(resizedKey),
        Body:   bytes.NewReader(buf.Bytes()),
    }
    _, err = r.S3Client.PutObject(uploadInput)
    if err != nil {
        return fmt.Errorf("upload failed: %w", err)
    }

    log.Printf("Resized and uploaded: %s", resizedKey)
    return nil
}

func main() {
    resizer := NewImageResizer("my-image-bucket")
    if err := resizer.ResizeAndUpload("input.jpg", 1024, 768); err != nil {
        log.Fatal(err)
    }
    fmt.Println("Service ready")
}
